### ISSUE TITLE
Move from ratelimit.proto to rls.proto in data-plane-api

### ISSUE THREAD

**Issue by junr03** [lyft/ratelimit#14]
https://github.com/envoyproxy/data-plane-api/blob/master/api/rls.proto

**Comment by jsedgwick** [comment]
@junr03 description seems wacky, do you mean that we want to migrate envoy's ratelimit service proto dependency from

https://github.com/envoyproxy/envoy/blob/master/source/common/ratelimit/ratelimit.proto

to

https://github.com/envoyproxy/data-plane-api/blob/master/envoy/service/ratelimit/v2/rls.proto

?

I can work on this once the intention is clarified.

**Comment by junr03** [comment]
Assigning back to myself. Will do as part of Lyft's work on this area for Q2
