### ISSUE TITLE
make bootstrap failing for 'github.com/Sirupsen/logrus'

### ISSUE THREAD

**Issue by amogh-plivo** [lyft/ratelimit#23]
When I tried to do a 'make bootstrap', I got this error.
 [ERROR]	Update failed for github.com/Sirupsen/logrus: The Remote does not match the VCS endpoint
[ERROR]	Failed to install: The Remote does not match the VCS endpoint
make: *** [bootstrap] Error 1 

The possible cause if that the logrus package has got renamed to 'github.com/sirupsen/logrus' from 'github.com/Sirupsen/logrus'. This should be fixed in glide files.

**Comment by junr03** [comment]
@amogh-plivo I can't replicate this. Both uppercase S and lowercase s work locally.

**Comment by junr03** [comment]
closing for now

**Comment by rwlincoln** [comment]
This issue may only arise if you are using a case-sensitive file system: https://github.com/golang/dep/issues/433#issuecomment-317146614
