### ISSUE TITLE
Resource Usage in Production

### ISSUE THREAD

**Issue by mjallday** [lyft/ratelimit#26]
What kind of resource (CPU + RAM) limits do you recommend when running this in your production environment? Any guidelines available publicly?

**Comment by junr03** [comment]
We (Lyft) currently run a ratelimit cluster that handles ~200-250k RPS with ~100 c4.xlarge aws instances. The machines run at about 40% CPU utilization, and ~20% RAM usage. All of our calls to the service have a 20ms timeout and while p999 gets close to it, our p99 is ~2ms. 

Is this what you were looking for?

**Comment by mjallday** [comment]
Yep, that's great. Looking for guidance on RAM/CPU under load and this helps me figure it out. Those instances have 7.5gb of memory so no issue running this. Thanks!

**Comment by georgasa** [comment]
Hello @junr03,

in my environment (as depicted below), a single ratelimit process can handle efficiently up to 2,5k RPS with one CPU utilization while if I go further (e.g. e.g. 6k RPS) ratelimit gets 2-3 CPUs!! Is this normal? I guess it sounds like very resource demanding application, doesn't it?

Thanks,
Apostolos
![image](https://user-images.githubusercontent.com/10513781/55592803-4d6da480-5742-11e9-87e0-d1ddf5e6a484.png)
