### ISSUE TITLE
Not meshing with ambassador

### ISSUE THREAD

**Issue by lemccarthy** [lyft/ratelimit#48]
I have managed to get past my previous difficulties with getting the actual app running, but now that I have, I can't seem to figure out how to get it to mesh with ambassador. Despite both lyft and datawire repos/docs repeatedly mentioning this as a drop-in solution for rate-limiting in ambassador, I can't actually find any example projects that combine these two technologies.

```
kubectl logs ratelimiter-0 -c ratelimit
time="2018-09-14T17:10:15Z" level=warning msg="statsd is not in use"
time="2018-09-14T17:10:15Z" level=warning msg="connecting to redis on tcp 127.0.0.1:6379 with pool size10"
time="2018-09-14T17:10:15Z" level=warning msg="Listening for HTTP on ':8080'"
time="2018-09-14T17:10:15Z" level=warning msg="Listening for debug on ':6070'"
time="2018-09-14T17:10:15Z" level=warning msg="Listening for gRPC on ':8081'"
````

This is what I see when I first start the service. My first question is, what is the difference between the 8080 and the 8081 endpoint? The 8081 endpoint is not mentioned in any of the documentation, and the docker-compose reference does not expose it. 

However when I attempt to curl `8080` on the ratelimit pod, I get a 404 not found error. When I curl `8081`, I get `curl: (56 Recv failure: Connection reset by peer)`. Directly curling the endpoints also does not appear in any form in the console output for the ratelimit app (the log level is set to debug).

My ambassador instance can see the mapping on the kubernetes service I have defined for ratelimit, and shows "tcp://ratelimiter:8080" on the list of RateLimitService. 

So I'm not sure where to go from here. Is the service supposed to 404 on 8080? The debug endpoint looks ok, and hitting `0:6070/rlconfig` accurately prints out my configs. I see no error messages either.

**Comment by junr03** [comment]
@lemccarthy a couple points:
1. I dont think we (lyft) has docs/repos mentioning ambassador. However, it would be nice to have folks at datawire expand their documentation explaining how they have setup ambassador with ratelimit.
2. 8080 is bound to the plain http server, and 8081 is bound to the gRPC server. This means that the gRPC calls should be made to 8081.
3. Sorry about no exposing the 8081 port on the docker-compose setup, that is my oversight. PR to fix https://github.com/lyft/ratelimit/pull/55.

**Comment by richarddli** [comment]
Yes, I think this really isn't a bug in the ratelimit service, it's really with how Ambassador handles descriptors. We (Ambassador team) are looking into this a bit more now. I think when rate limiting was initially implemented it was tested with a custom rate limiting impl which was less sophisticated than this service.

**Comment by soluwalana** [comment]
@lemccarthy I found a workaround for meshing with the way that Ambassador is sending the RateLimitDescriptor

Change the for loop in config_impl.go GetLimit to look like this:

```
for descriptorsMap != nil {
		var nextDescriptor *rateLimitDescriptor
		for _, entry := range descriptor.Entries {
			// First see if key_value is in the map. If that isn't in the map we look for just key
			// to check for a default value.
			finalKey := entry.Key + "_" + entry.Value
			logger.Debugf("looking up key: %s", finalKey)
			nextDescriptor = descriptorsMap[finalKey]

			if nextDescriptor == nil {
				finalKey = entry.Key
				logger.Debugf("looking up key: %s", finalKey)
				nextDescriptor = descriptorsMap[finalKey]
			}

			if nextDescriptor == nil {
				continue
			}

			if nextDescriptor.limit != nil {
				logger.Debugf("found rate limit: %s", finalKey)
				rateLimit = nextDescriptor.limit
				descriptorsMap = nil
				break
			}
			descriptorsMap = nextDescriptor.descriptors
		}
		if nextDescriptor == nil {
			descriptorsMap = nil
		}
	}
``` 

That should resolve your issue

**Comment by lemccarthy** [comment]
> @lemccarthy I found a workaround for meshing with the way that Ambassador is sending the RateLimitDescriptor
> 
> Change the for loop in config_impl.go GetLimit to look like this:
> 
> ```
> for descriptorsMap != nil {
> 		var nextDescriptor *rateLimitDescriptor
> 		for _, entry := range descriptor.Entries {
> 			// First see if key_value is in the map. If that isn't in the map we look for just key
> 			// to check for a default value.
> 			finalKey := entry.Key + "_" + entry.Value
> 			logger.Debugf("looking up key: %s", finalKey)
> 			nextDescriptor = descriptorsMap[finalKey]
> 
> 			if nextDescriptor == nil {
> 				finalKey = entry.Key
> 				logger.Debugf("looking up key: %s", finalKey)
> 				nextDescriptor = descriptorsMap[finalKey]
> 			}
> 
> 			if nextDescriptor == nil {
> 				continue
> 			}
> 
> 			if nextDescriptor.limit != nil {
> 				logger.Debugf("found rate limit: %s", finalKey)
> 				rateLimit = nextDescriptor.limit
> 				descriptorsMap = nil
> 				break
> 			}
> 			descriptorsMap = nextDescriptor.descriptors
> 		}
> 		if nextDescriptor == nil {
> 			descriptorsMap = nil
> 		}
> 	}
> ```
> 
> That should resolve your issue

Has this function change made its way into a commit somewhere, or do I need to copy this manually in addition to getting the commit that fixes the port expose issue?

**Comment by soluwalana** [comment]
You would need to make the change in a fork of your own, I was just sharing something that worked for us.

**Comment by mattklein123** [comment]
Closing this out. Please follow up with the Ambassador team for further issues.
