### ISSUE TITLE
Migrate from glide to dep

### ISSUE THREAD

**Issue by aaslamin** [lyft/ratelimit#49]
Hi Lyft,

Thank you for the awesome rate limiter service! 

Now that the Go community has settled on dep, should the dependency management be switched from glide to dep? The glide repo is [recommending people to migrate over](https://github.com/Masterminds/glide#golang-dep):

> The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

I don't mind taking this on if it's something you would like to do.

**Comment by junr03** [comment]
hi @aaslamin internally at Lyft we still use glide for our dependency management. My preference would be to keep this consistent until lyft migrates forward. I will update this ticket with news about that, as it unfolds, and keep you in the loop. Thanks!

**Comment by aaslamin** [comment]
Thanks for the info @junr03!

Turns out migrating to dep may not be a huge benefit given go modules is close to being finalized. Go 1.11 currently includes preliminary support for modules with [hopes of it eventually being fully incorporated in Go 1.12](https://research.swtch.com/vgo-accepted).

With that said, many projects are already utilizing modules in anticipation of its official release.

**Comment by mattklein123** [comment]
Going to close this out for now.
