### ISSUE TITLE
Is there any way to set up credentials for Redis ?

### ISSUE THREAD

**Issue by medalliaerlich** [lyft/ratelimit#61]
I'm using `ratelimit` with an existing Redis cluster which has credentials. Is there any way to configure them? or should I fork the project?

**Comment by medalliaerlich** [comment]
Hi, any update on this?
Where should I start with if I had to modify the code to support credentials?

**Comment by mattklein123** [comment]
I'm not familiar with redis credentials, but PRs appreciated. I would have a look at the redis connection code.
