### ISSUE TITLE
Is there any way to check a limit without incrementing it?

### ISSUE THREAD

**Issue by gi-wg2** [lyft/ratelimit#62]
I would like to check a limit without incrementing it, which would be logical equivalent to do `hits_addend = 0`. As proto3 doesn't distinguish between zero and null, this would however not be possible (handled in https://github.com/lyft/ratelimit/blob/master/src/redis/cache_impl.go#137).

Is there any way to model this in the current setup?

The use case I want to solve is a auth server, where I want to do rate limitation based on invalid credentials such that all requests will give 429 after e.g. 10 invalid requests per minute.

**Comment by mattklein123** [comment]
This is not currently supported though I'm unclear why this is needed for your auth example?
