### ISSUE TITLE
Deploying config as Kubernetes config map not working

### ISSUE THREAD

**Issue by alexhcheng** [lyft/ratelimit#70]
I'm able to build and create a docker image (with a config embedded) and run on kubernetes.

I'm trying to extract the same config to be used as a config map

kubectl create configmap my-config --from-file=mt-ratelimit/config/config.yaml

I mounted the config map as a volume

Environment:
      LOG_LEVEL:             INFO
      REDIS_SOCKET_TYPE:     tcp
      REDIS_URL:             ratelimit-store:6379
      RUNTIME_ROOT:          /data
      RUNTIME_SUBDIRECTORY:  ratelimit2
      USE_STATSD:            false
    Mounts:
      /data/ratelimit2/config from config-volume (rw)

Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ratelimit-config
    Optional:  false

but logs are showing error loading:

time="2019-03-18T23:28:41Z" level=warning msg="runtime: error reading /data/ratelimit2/config/..data: read /data/ratelimit2/config/..data: is a directory"
time="2019-03-18T23:28:41Z" level=warning msg="connecting to redis on tcp ratelimit-store:6379 with pool size 10"
time="2019-03-18T23:28:41Z" level=error msg="error loading new configuration from runtime: config...3983_18_03_23_27_49.611881932.config.yaml: error loading config file: yaml: mapping values are not allowed in this context"

when i sh into the pod, i see this
/data/ratelimit2/config # ls -al
total 12
drwxrwxrwx    3 root     root          4096 Mar 18 23:27 .
drwxr-xr-x    3 root     root          4096 Mar 18 23:28 ..
drwxr-xr-x    2 root     root          4096 Mar 18 23:27 ..3983_18_03_23_27_49.611881932
lrwxrwxrwx    1 root     root            31 Mar 18 23:27 ..data -> ..3983_18_03_23_27_49.611881932
lrwxrwxrwx    1 root     root            18 Mar 18 23:27 config.yaml -> ..data/config.yaml

i also tried creating the configmap using 
kubectl create configmap my-config --from-file=ratelimitconfig.yaml=config.yaml

but got the same result.

**Comment by alexhcheng** [comment]
ok, looks like i just need to add this env variable, and then the runtime library behaves properly
        - name: RUNTIME_IGNOREDOTFILES
          value: "true"

**Comment by murtuza-kolasavala** [comment]
Thanks a lot man, This resolved my issue as well.
