### ISSUE TITLE
Redis usage

### ISSUE THREAD

**Issue by georgasa** [lyft/ratelimit#72]
Hello,

I monitored Redis while ratelimit was in service and I noticed only increments and expiration sets. No reads read requests towards DB by the application so I'm wondering what's the purpose of deploying a Redis with ratelimit? Also I observed random expiration times (many times quite long e.g. 240 seconds or more). Why is that? What's the purpose of leaving keys in DB for some random time?

Thank you,
Apostolos

**Comment by mattklein123** [comment]
1) INC returns the new value, there is no reason to read separately.
2) Random expiration ensures that Redis does not get locked up handling expirations at the same time.

**Comment by georgasa** [comment]
Thank you for your answer. And why not to apply key expiration just once (at the time the key is created) and not during every single increment? The CPU needs are pretty high for ratelimit so I'm wondering if there are any plans for some optimization.
