### ISSUE TITLE
Why do you apply a different (random) expiration time whenever the key is accessed?

### ISSUE THREAD

**Issue by georgasa** [lyft/ratelimit#80]
Hello,

Whenver ratelimit access a specific key to increase it, it re-applies also a different (random) expiration time on the key. So 2 actions are performed against DB instead of the one that really needed (the increment). 

So, I was wondering, why not to apply key expiration just once (at the time the key is created) and not during every single increment? The CPU demands see to be pretty high for ratelimit so I'm wondering if there are any plans for some optimization.

Thank you,
Apostolos

**Comment by mattklein123** [comment]
> So, I was wondering, why not to apply key expiration just once (at the time the key is created) and not during every single increment?

How would you know when the key is created? Feel free to propose PRs if you see optimization opportunities.

**Comment by georgasa** [comment]
> How would you know when the key is created?

Ratelimit is the one that creates the key so it knowswhen it is created. Let me elaborate it a bit with a scenario ...

Let's say that we have per second rate limitation and whithin a second 10k messages come. Ratelimit will create the key in Redis by adding the appropriate timestamp in key's name and will:

- increase its value by +1 whenever a new message comes within this second and
- re-apply a random expiration time on the key.

So within this single second, ratelimit will increase the value of the key 10k times and will change its expiration time the very same amount of times. Why is that needed? Why do we need 20k opeations towards DB instead of 10k+1?

**Comment by mattklein123** [comment]
> So within this single second, ratelimit will increase the value of the key 10k times and will change its expiration time the very same amount of times. Why is that needed? Why do we need 20k opeations towards DB instead of 10k+1?

Because if you have N ratelimit instances it's impossible to know who created the key.

**Comment by georgasa** [comment]
By using this Redis command: https://redis.io/commands/EXISTS

the first instance of the cluster of N ratelimits will get back a "0" so it will create the key and apply a random expiration time.
All the other instances will get back an "1" so will just increase the value of the key during the same second. 

In such case, and for my example above, we would have only N*(10k + 1) + 1 operations insetad of 2N*10k per second. e.g. for a cluster with 3 ratelimit instances, we would have 30.004 hits towards DB per second, instead of 60.000 which is now the case.

**Comment by mattklein123** [comment]
Sorry I don't follow. Now on every operation every instance has to run an EXISTS command. This seems about the same to me and more complicated. Feel free to run some benchmarks and propose a PR if you can show a performance improvement.

**Comment by georgasa** [comment]
ok, I'll do so and let you know.

**Comment by georgasa** [comment]
I tested a custom ratelimit build/hack with the Redis keys only being incremented (wihout changing their expiration everytime when they are incremented) but I didn't notice any improvement as far as the ratelimit's CPU consumption is concerned :(

I have the following environment:

- A simulator producing 6000 http2 messages per second 
- One Envoy acting as LB
- Three ratelimit instances
- One common Redis DB for all ratelimit instances

Under these circumastancies/deployment, every ratelimit instance concumes almost one vCPU. If I increase the incoming rate, ratelimit consumes  more than 1vCPU and becomes underilable as it can't limit the expected ratio (it let's more traffic than the desired one to reach the backends).

Do you have any engineering rules/performance test results that declare how much traffic (gRPC calls per second) a single ratelimit instance handle properly (and not violate the expected success ration)?

Thank you
