### ISSUE TITLE
Rate Limit Service: Resiliency Question

### ISSUE THREAD

**Issue by xuorig** [lyft/ratelimit#91]
Kind of a meta question 🤓possibly for the folk at Lyft. I'm curious on how people make sure the rate limit service itself is resilient to abuse / high traffic.

- How do you rate limit the rate limit service?
- What about the fallback strategy? Defaulting to not rate limited potentially affects the rest of the system, and defaulting to rate limited essentially stops all users from interacting with the system.

**Comment by mattklein123** [comment]
In general we always fail open for rate limit

**Comment by xuorig** [comment]
Thanks, will close.
